kind: Deployment
apiVersion: apps/v1

metadata:
  name: camera-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camera-app
  template:
    metadata:
      labels:
        app: camera-app
    spec:
      containers:
        - name: camera-app-container
          securityContext:
            privileged: true
          command: ["python3", "-u", "/app/test_3.py"]
          env:
            - name: LD_LIBRARY_PATH
              value: /opt/vc/lib
          image: acrdoorbell.azurecr.io/testapp2:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: udev
              mountPath: /run/udev
              readOnly: true
      volumes:
        - name: udev
          hostPath:
            path: /run/udev

      imagePullSecrets:
        - name: acr-pull
