kind: Deployment
apiVersion: apps/v1

metadata:
  name: camera-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camera-app
  template:
    metadata:
      labels:
        app: camera-app
    spec:
      containers:
        - name: sample-ml-workload-container
          securityContext:
            privileged: true
          env:
            - name: LD_LIBRARY_PATH
              value: /opt/vc/lib
          image: acrdoorbell.azurecr.io/testapp2:latest
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /dev/
              name: devDirectory
              readOnly: true
            - name: udev
              mountPath: /run/udev
              readOnly: true
      volumes:
        - name: devDirectory
          hostPath:
            path: /dev/
        - name: udev
          hostPath:
            path: /run/udev
            
      imagePullSecrets:
        - name: acr-pull
