apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: device-iothub-external-secret
spec:
  # RefreshInterval is the amount of time before the values reading again from the SecretStore provider
  refreshInterval: 1h
  # SecretStoreRef defines which SecretStore to use when fetching the secret data
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-azkv-secret-store
  # the target describes the secret that shall be created
  target:
    name: device-iot-hub-conn-str
    # Owner means that the secret is created and controlled by ESO
    creationPolicy: Owner

  # Data defines the connection between the Kubernetes Secret keys and the Provider data
  data:
    # The client ID and secret should be of a service principal that is authorized to pull images
    # from the ACR referenced in the dockerconfigjson
    - secretKey: iot-hub-connection-string
      remoteRef:
        key: place-holder-value
