apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: cluster-azkv-secret-store
spec:
  provider:
    azurekv:
      tenantId: d2e5ac16-7068-4b2d-995b-3924af59cc7a
      vaultUrl: https://doorbellkv.vault.azure.net/
      authSecretRef:
        # points to the secret that contains
        # the azure service principal credentials
        clientId:
          name: azkv-secret
          key: ClientID
          namespace: external-secrets
        clientSecret:
          name: azkv-secret
          key: ClientSecret
          namespace: external-secrets
